### ISSUE TITLE
取消Repo Lockdown的Action

### ISSUE THREAD

**Issue by IceSoulHanxi** [cogbt/COGBT#2]
https://github.com/cogbt/COGBT/blob/stable/.github/workflows/lockdown.yml
该文件是QEMU引导用户到gitlab主仓库中提交PR的自动任务, 会直接拒绝其他对该仓库用户进行PR, 建议将其删除或者关闭这个Action

**Comment by specialpointcentral** [comment]
Fixed: https://github.com/cogbt/COGBT/commit/1c7f6babdc7fd7d2ae92cd939730c6172be986ca
